[versions]
androidGradlePlugin = "8.8.0"
kotlin = "1.8.10"
kotlinxSerialization = "1.9.22"
dokka = "1.9.20"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinxSerialization" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
