name: Update Changelog
on:
  # Runs whenever a new tag is pushed
  push:
    tags:
      - '*.*.*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Update Changelog job
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update Changelogs
        run: |
          changelogs=("$(find "connectors" -type f -name "CHANGELOG.md")")
          version=$GITHUB_REF_NAME
          date=$(date +"%Y-%m-%d")
          
          for changelog in ${changelogs[*]}
          do
          echo "$changelog"
          # Replace the line containing "## Unreleased" with new version and date
          sed -i '' -e "s/^## Unreleased$/## [$v] - $date/" "$changelog"
          done
