name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Run unit tests
        run: ./gradlew test
        env:
          YOSPACE_USERNAME: ${{ secrets.YOSPACE_USERNAME }}
          YOSPACE_PASSWORD: ${{ secrets.YOSPACE_PASSWORD }}
