name: Update player version
run-name: ${{ format('Update player version to {0}', inputs.version) }}${{ inputs.dryRun == true && ' (dry run)' || '' }}
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Player version, e.g. "10.0.0"'
        required: true
        type: string
      dryRun:
        description: "Dry run: don't actually push anything."
        required: false
        default: false
        type: boolean

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.THEOPLAYER_BOT_APP_ID }}
          private-key: ${{ secrets.THEOPLAYER_BOT_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Configure Git user
        run: |
          git config user.name 'theoplayer-bot[bot]'
          git config user.email '873105+theoplayer-bot[bot]@users.noreply.github.com'
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          # https://github.com/gradle/actions/blob/v6.0.0/README.md#licensing-notice
          cache-disabled: true
      - name: Update player version
        run: ./gradlew :updatePlayerVersion -PsdkVersion=$VERSION
        env:
          VERSION: ${{ inputs.version }}
      - name: Commit
        # language=bash
        run: |
          git add .
          git commit -m "Update player to version $VERSION"
        env:
          VERSION: ${{ inputs.version }}
      - name: Push to origin
        if: inputs.dryRun == false
        # language=bash
        run: |
          git push origin
        env:
          VERSION: ${{ inputs.version }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
